#!/bin/bash
# Test script for search_replace guards

set -e

echo "=== Testing search_replace Guards ==="
echo ""

REPO_ROOT="/Users/chamseddinebouzaiene/Documents/dodo"
TEST_DIR="$REPO_ROOT/.test_guards"

# Clean up any previous test
rm -rf "$TEST_DIR"
mkdir -p "$TEST_DIR"

cd "$TEST_DIR"

echo "1. Testing normal edit (should work)..."
cat > normal.go <<'EOF'
package main

func hello() {
	println("Hello")
}
EOF

# Create a simple test program to call search_replace
cat > test.json <<'EOF'
{
  "file_path": ".test_guards/normal.go",
  "old_string": "func hello() {\n\tprintln(\"Hello\")\n}",
  "new_string": "func hello() {\n\tprintln(\"Hello, World!\")\n}"
}
EOF

echo "✓ Normal edit test file created"
echo ""

echo "2. Testing binary file rejection..."
# Create a fake binary file
echo -e "\x89PNG\x0D\x0A\x1A\x0A" > binary.png
echo "✓ Binary file created (.png)"
echo ""

echo "3. Testing generated file rejection..."
cat > generated.go <<'EOF'
// Code generated by protoc-gen-go. DO NOT EDIT.
package pb

type Message struct {
	ID string
}
EOF
echo "✓ Generated file created"
echo ""

echo "4. Testing large edit warning (200+ lines)..."
cat > large.go <<'EOF'
package main

func bigFunction() {
EOF

# Generate 250 lines
for i in {1..250}; do
  echo "	// Line $i" >> large.go
done

echo "}" >> large.go
echo "✓ Large file created (250 lines)"
echo ""

echo "5. Testing indentation mismatch..."
cat > tabs.go <<'EOF'
package main

func tabbed() {
	if true {
		return
	}
}
EOF
echo "✓ Tabs file created"
echo ""

echo "=== Test Files Created ==="
echo "Directory: $TEST_DIR"
echo ""
echo "To test manually:"
echo "1. Normal edit: Should succeed"
echo "2. Binary file: Should reject with 'File type not allowed'"
echo "3. Generated file: Should reject with 'File appears to be generated'"
echo "4. Large edit: Should warn at 200 lines, reject at 500+"
echo "5. Indentation: Should fail with helpful error showing file uses tabs/spaces"
echo ""
echo "Test files are ready. Run your agent with tasks that use search_replace on these files."

